#!/usr/bin/python
#
# Connects to the info-beamer node (localhost, 4444 over a UDP socket) to send
# commands from keyboard or presenter.
#
# https://info-beamer.com/doc/info-beamer#node.event/data
#

import sys
import time
import socket
import argparse


# config
SOCK_IP = {
    1: '127.0.0.1',
    2: '127.0.0.1',
    3: '127.0.0.1',
    4: '127.0.0.1',
}
SOCK_PORT = 4444
ROOMS = SOCK_IP.keys()
COMMANDS = ["forward", "backward", "start", "reset"]

# arguments
desc = """Sends a command to info-beamer Pi."""
parser = argparse.ArgumentParser(description=desc)
parser.add_argument('-r','--room', type=int, choices=ROOMS, default=1,
                    help="""The room where the Pi resides (selects the IP
                    address to connect to the Pi in the given room). Choose out
                    of {}.""".format(ROOMS))
parser.add_argument('command', type=str, choices=COMMANDS, help="""Command to
                    send to Pi. Choose out of {}.""".format(COMMANDS))
args = parser.parse_args()


# create socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)


def send(data):
    sock.sendto(data, (SOCK_IP[args.room], SOCK_PORT))
    print >>sys.stderr, "SENT >>> ", data

def send_command(cmd):
    send('room/cmd:%s' % cmd)

def main():
    send_command(args.command)


if __name__ == "__main__":
    main()
