#!/usr/bin/python
#
# https://info-beamer.com/doc/info-beamer#usage How do I get the current time?
#
import sys
import time
import pytz
import socket
from calendar import timegm
from datetime import datetime, date

# Config
startdate = date(2017,11,13)
diff = None
timezone = pytz.timezone('Europe/Vienna')

# Fake time in UTC
#diff = datetime(2017,11,13,8,59,45) - datetime.utcnow()


def current_time():
    now = datetime.utcnow()
    if diff:
        now += diff
    # converts timestamp to locale settings
    now = now.replace(tzinfo=pytz.utc)
    now = now.astimezone(timezone)
    now = now.replace(tzinfo=None)
    timestamp = timegm(now.timetuple()) + now.microsecond / 1000000.
    return now, timestamp

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def send(data):
    sock.sendto(data, ('127.0.0.1', 4444))
    print >>sys.stderr, "SENT >>> ", data

def send_clock(now, ts):
    day = (now.date() - startdate).days
    since_midnight = (
        now -
        now.replace(hour=0, minute=0, second=0, microsecond=0)
    )
    since_midnight = since_midnight.seconds + since_midnight.microseconds / 1000000.

    send('room/clock/day:%d' % day)
    send('room/clock/set:%f' % ts)
    send('room/clock/midnight:%f' % since_midnight)


def main():
    while 1:
        now, ts = current_time()
        if now.year < 2000:
            print >>sys.stderr, "too soon"
            time.sleep(1)
            continue
        send_clock(now, ts)
        time.sleep(2)

if __name__ == "__main__":
    main()
